name: Build and Run

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup and run linter
      run: |
        pip install cpplint
        cpplint  --filter=-legal --linelength=100 *.cpp

    - name: tshirts pass
      run: |
        g++ -Wall -Wextra -Werror tshirts.cpp TestTshirtsize.cpp -o tshirts.out
        bash .github/workflows/expectfail.sh ./tshirts.out

    - name: misaligned pass
      run: |
        g++ -Wall -Wextra -Werror misaligned.cpp TestPrintColorMap.cpp -o misaligned.out
        bash .github/workflows/expectfail.sh ./misaligned.out

    - name: alerter pass
      run: |
        g++ -Wall -Wextra -Werror weatherreport.cpp TestWeatherReport.cpp -o weatherreport.out
        bash .github/workflows/expectfail.sh ./weatherreport.out
